apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polybot-cluster-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "polybot.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: polybot-cluster-role
  apiGroup: rbac.authorization.k8s.io
